### ISSUE TITLE
Specify dependencies versions in requirements.txt. 

### ISSUE THREAD

**Issue by Andrea-Valentini** [fissoreg/papers-search#6]
As the dependencies versions are not specified, the latest versions are considered by default.
This should be corrected as the command  `from jina.types.document.generators import from_csv` in backend/app.py is not consistent with jina latest version.

**Comment by fissoreg** [comment]
Thank you @SoFish1 ! This is going to be useful for #4 too. PRs are welcome :)

**Comment by Andrea-Valentini** [comment]
Moreover, as there are a lot of dependencies, I'd suggest to handle them with [poetry](https://python-poetry.org/).
